### ISSUE TITLE
Not licensed

### ISSUE THREAD

**Issue by jabbenseth** [saadi-tech/kidnapped_robot_finder#1]
Hi,

your work looks interesting. Can you add a License that clarifies its usage?

Best Regards

**Comment by saadi-tech** [comment]
Hello Jannik.
Thank you for your interest. I will add license, I intend to keep it
completely open source.

Thank you.

Regards,
Saas

**Comment by saadi-tech** [comment]
MIT license added. Thank you @jabbenseth
